---
title: "PrelimAnalysis_19SEP2017"
author: "Forest Schenck"
date: "September 19, 2017"
output: pdf_document
---

#PACKAGES
```{r}
library(dplyr)
library(sciplot)
library(car)
library(lme4)
library(ggplot2)

source("http://faraway.neu.edu/data/Rprofile")
```

#Importing/wrangling data
```{r}
bwe <- read.csv("bwe_data.csv") #importing from dropbox
str(bwe)

bwe$rep <- as.factor(bwe$rep)
bwe$bin <- as.factor(bwe$bin)

bwe$cells.absent <- 1-bwe$cells.present
bwe$lesion.absent <- 1-bwe$lesion

bwe.pot <- bwe %>%
  #filter(cell.mg < 100) %>% #omitting large cell values
  group_by(diversity, pot, treatment, bin, rep) %>%
  summarize(Lprevalence = mean(lesion, na.rm = T), Lpresent = sum(lesion, na.rm = T), Labsent = sum(lesion.absent, na.rm = T), Lseverity = mean(lc.FS, na.rm = T)/100, Cprevalence = mean(cells.present, na.rm = T), Cpresent = sum(cells.present, na.rm = T), Cabsent = sum(cells.absent, na.rm = T), Cseverity = mean(cell.mg, na.rm = T))

bwe.pot$Lpresent <- as.numeric(bwe.pot$Lpresent)
bwe.pot$Cpresent  <- as.numeric(bwe.pot$Cpresent)

bwe.pot$Cseverity.round <- ceiling(bwe.pot$Cseverity) #rounding Cseverity to nearest integer > than Cseverity value

bwe.pot$Lprevalence.arcsine <- asin(sqrt(bwe.pot$Lprevalence)) #arcsine transformation of Lprevalence data
bwe.pot$Lprevalence.logit <- log((bwe.pot$Lprevalence-0.001)/(1-(bwe.pot$Lprevalence-0.001))) #logit transformation of Lprevalence data

bwe.pot$Lseverity.arcsine <-asin(sqrt(bwe.pot$Lseverity)) #arcsine transformation of Lprevalence data
bwe.pot$Lseverity.logit <- log((bwe.pot$Lseverity)/(1-bwe.pot$Lseverity)) #logit transformation of Lseverity data

bwe.pot$Cprevalence.arcsine <- asin(sqrt(bwe.pot$Cprevalence)) #arcsine transformation of Cprevalence data
bwe.pot$Cprevalence.logit <- log((bwe.pot$Cprevalence + 0.001)/(1 - (bwe.pot$Cprevalence + 0.001))) #logit transformation of Cprevalence data
bwe.pot$Cprevalence.logit[7] <- log((bwe.pot$Cprevalence [7] - 0.001)/(1 - (bwe.pot$Cprevalence[7] - 0.001))) #logit transformation of Cprevalence data continued

bwe.pot$Cseverity.sqrt <- sqrt(bwe.pot$Cseverity) #sqrt transformation of Cseverity data

str(bwe.pot)
head(bwe.pot)

bwe.pot.Lintensity <- bwe %>%
  filter(lesion > 0) %>%
  group_by(diversity, pot, treatment, bin, rep) %>%
  summarize(Lintensity= mean(lc.FS, na.rm = T)/100) #subsetting data by lesion prevalence > 0 to measure lesion intensity

bwe.pot.Lintensity$Lintensity.arcsine <- asin(sqrt(bwe.pot.Lintensity$Lintensity)) #arcsine transformation of Lintensity
bwe.pot.Lintensity$Lintensity.logit <- log(bwe.pot.Lintensity$Lintensity/(1-bwe.pot.Lintensity$Lintensity))

bwe.pot.Cseverity <- bwe %>%
  filter(cell.mg < 10000) %>% #omitting large cell values
  group_by(diversity, pot, treatment, bin, rep) %>%
  summarize(Cseverity = mean(cell.mg, na.rm = T))

bwe.pot.Cintensity <- bwe %>%
  filter(cells.present > 0) %>%
  #filter(cell.mg < 100) %>% #omitting large cell values
  group_by(diversity, pot, treatment, bin, rep) %>%
  summarize(Cintensity = mean(cell.mg, na.rm = T)) #subsetting data by cell presence > 0 to measure cell intensity

bwe.pot.Cintensity$Cintensity.sqrt <- sqrt(bwe.pot.Cintensity$Cintensity) #sqrt transformed C intensity

bwe.bin.Cintensity <- bwe %>% #filter out bin with only monocultures
  filter(cells.present > 0) %>%
  filter(bin != '14') %>%
  group_by(diversity, treatment, bin) %>%
  summarize (Cintensity = mean(cell.mg, na.rm = T)) #subsetting data by cell presence >0 at bin level

bwe.bin.Cintensity$Cintensity.sqrt <- sqrt(bwe.bin.Cintensity$Cintensity)
```

#ANALYSES
##Lesion Prevalence
```{r}
#Analyses
#Lprev.model <-  glm(cbind(Lpresent, Labsent) ~ treatment*diversity, family = binomial, data = bwe.pot)

#Lprev.model <- glm(cbind(Lpresent, Labsent) ~ treatment/diversity, family = binomial, data = bwe.pot)

#Lprev.model <- glmer(cbind(Lpresent, Labsent) ~ treatment * diversity + (1|bin), family = binomial, data = bwe.pot) #random effects model
#anova(Lprev.model, test = "LR")
#Anova(Lprev.model) ##use this for P values (package = car)

hist(bwe.pot$Lprevalence.arcsine)

Lprev.model <- aov(Lprevalence.arcsine ~ diversity * treatment + Error(bin), data = bwe.pot)
summary(Lprev.model)

Lprev.model2 <- aov(Lprevalence.arcsine ~ diversity * treatment, data = bwe.pot)
plot(Lprev.model2)
hist(residuals(Lprev.model2), main = "Arcsine Transformation")
shapiro.test(residuals(Lprev.model2))
leveneTest(Lprev.model2)

#Figure
p <- ggplot(bwe.pot, aes(x = treatment, y = Lprevalence, fill = diversity)) + 
  scale_fill_manual(values = c("white", "grey", "")) +
  geom_violin(position = position_dodge(1)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(1), dotsize  = 0.5) +
  stat_summary(fun.y = mean, geom = "point", size = 3, color = "red", position = position_dodge(1)) +
  labs(x = "Temperature Treatment", y = "Proportion of shoots with lesions") +
  theme_classic()
p

p <- ggplot(bwe.pot, aes(x = bin, y = Lprevalence, fill = treatment)) + 
  scale_fill_manual(values = c("white", "grey")) +
  geom_violin(position = position_dodge(1)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(1), dotsize  = 0.5) +
  stat_summary(fun.y = mean, geom = "point", size = 3, color = "red", position = position_dodge(1)) +
  labs(x = "Bin", y = "Proportion of shoots with lesions") +
  theme_classic()
p
```

##Lesion severity
```{r}
#Analyses
hist(bwe.pot$Lseverity.arcsine)

Lsev.model <- aov(Lseverity.arcsine ~ diversity * treatment + Error(bin), data = bwe.pot)
summary(Lsev.model)

#Lsev.model <- glmer(Lseverity ~ diversity * treatment + (1|bin), family = gaussian, data = bwe.pot) #checking to see if glmer formula structure correct
#anova(Lsev.model)

Lsev.model2 <- aov(Lseverity.arcsine ~ diversity * treatment, data = bwe.pot)
plot(Lsev.model2) #distribution looks ok
hist(residuals(Lsev.model2), main = 'arcsine transformation')
shapiro.test(residuals(Lsev.model2))
leveneTest(Lsev.model2)

#Figures
p <- ggplot(bwe.pot, aes(x = treatment, y = Lseverity)) + 
  #scale_fill_manual(values = c("white", "grey")) +
  geom_violin(position = position_dodge(1)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(1), dotsize  = 0.5) +
  stat_summary(fun.y = mean, geom = "point", size = 3, color = "red", position = position_dodge(1)) +
  labs(x = "Temperature Treatment", y = "Proportion of leaf cover by lesions") +
  theme_classic()
p

p <- ggplot(bwe.pot, aes(x = bin, y = Lseverity, fill = treatment)) + 
  scale_fill_manual(values = c("white", "grey")) +
  geom_violin(position = position_dodge(1)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(1), dotsize  = 0.5) +
  stat_summary(fun.y = mean, geom = "point", size = 3, color = "red", position = position_dodge(1)) +
  labs(x = "Bin", y = "Proportion of leaf cover by lesions") +
  theme_classic()
p

##Lesion INTENSITY only for pots with disease
Lintensity.model <- aov(Lintensity.arcsine ~ treatment * diversity + Error(bin), data = bwe.pot.Lintensity)
summary(Lintensity.model)

Lintensity.model2 <- aov(Lintensity.arcsine ~ treatment * diversity, data = bwe.pot.Lintensity)
summary(Lintensity.model2)
plot(Lintensity.model2)
hist(residuals(Lintensity.model2))
shapiro.test(residuals(Lintensity.model2))
leveneTest(Lintensity.model2)

#Figures
p <- ggplot(bwe.pot.Lintensity, aes(x = treatment, y = Lintensity)) + 
  #scale_fill_manual(values = c("white", "grey")) +
  geom_violin(position = position_dodge(1)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(1), dotsize  = 0.5) +
  stat_summary(fun.y = mean, geom = "point", size = 3, color = "red", position = position_dodge(1)) +
  labs(x = "Temperature Treatment", y = "Proportion of diseased leaf cover by lesions") +
  theme_classic()
p

p <- ggplot(bwe.pot.Lintensity, aes(x = bin, y = Lintensity, fill = treatment)) + 
  scale_fill_manual(values = c("white", "grey")) +
  geom_violin(position = position_dodge(1)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(1), dotsize  = 0.5) +
  stat_summary(fun.y = mean, geom = "point", size = 3, color = "red", position = position_dodge(1)) +
  labs(x = "Bin", y = "Proportion of diseased leaf cover by lesions") +
  theme_classic()
p

```

##Cell Prevalence
```{r}
#Analyses
#Cprev.model <-  glm(cbind(Cpresent, Cabsent) ~ treatment + treatment:diversity, family = binomial, data = bwe.pot)
#Cprev.model <- glm(cbind(Cpresent, Cabsent) ~ treatment/diversity, family = binomial, data = bwe.pot)
#Cprev.model <- glmer(cbind(Cpresent, Cabsent) ~ treatment * diversity + (1|bin), family = binomial, data = bwe.pot)
#Cprev.model <- glmer(Cprevalence ~ treatment * diversity + (1|bin), family = poisson, data = bwe.pot)
#anova(Cprev.model, test = "LR")
#Anova(Cprev.model)

hist(bwe.pot$Cprevalence.arcsine)

Cprev.model <- aov(Cprevalence.arcsine ~ diversity * treatment + Error(bin), data = bwe.pot)
summary(Cprev.model)

Cprev.model2 <- aov(Cprevalence.arcsine ~ treatment * diversity, data = bwe.pot)
summary(Cprev.model2)
plot(Cprev.model2)
hist(residuals(Cprev.model2))
shapiro.test(residuals(Cprev.model2))
leveneTest(Cprev.model2)

#Figures
p <- ggplot(bwe.pot, aes(x = treatment, y = Cprevalence, fill = diversity)) + 
  scale_fill_manual(values = c("white", "grey", "")) +
  geom_violin(position = position_dodge(1)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(1), dotsize  = 0.5) +
  stat_summary(fun.y = mean, geom = "point", size = 3, color = "red", position = position_dodge(1)) +
  labs(x = "Temperature Treatment", y = "Proportion of shoots with Laby cells detected") +
  theme_classic()
p

p <- ggplot(bwe.pot, aes(x = bin, y = Cprevalence, fill = treatment)) + 
  scale_fill_manual(values = c("white", "grey")) +
  geom_violin(position = position_dodge(1)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(1), dotsize  = 0.5) +
  stat_summary(fun.y = mean, geom = "point", size = 3, color = "red", position = position_dodge(1)) +
  labs(x = "Bin", y = "Proportion of shoots with Laby cells detected") +
  theme_classic()
p
```

##Cell severity
```{r}
#Analyses ##DATA IS NOT NORMALLY DISTRIBUTED?

#Csev.model <- glm(Cseverity ~ treatment/diversity, family = poisson, data = bwe.pot)
#Anova(Csev.model)
#anova(Csev.model, test = "LR")

#standard poisson glm with rounded cell/mg values
#Anova(Csev.model <- glm(Cseverity.round ~ treatment/diversity, family = poisson, data = bwe.pot))

hist(bwe.pot$Cseverity)
hist(bwe.pot$Cseverity.sqrt)

Csev.model <- aov(Cseverity.sqrt ~ diversity * treatment + Error(bin), data = bwe.pot)
summary(Csev.model)

Csev.model2 <- aov(Cseverity.sqrt ~ diversity * treatment, data = bwe.pot)
summary(Csev.model2)
plot(Csev.model2)
hist(residuals(Csev.model2))
shapiro.test(residuals(Csev.model2))
leveneTest(Csev.model2)

#exploratory figures
p <- ggplot(bwe.pot, aes(x  = treatment, y = Cseverity, fill = diversity)) +
  scale_fill_manual(values = c("white", "grey")) +
  geom_violin(position = position_dodge(1)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(1), dotsize  = 0.5) +
  #stat_summary(fun.y = mean, geom = "point", size = 3, color = "red", position = position_dodge(1)) +
  labs(x = "Temperature Treatment", y = "Laby cells / mg") +
  ylim(0, 100) +
  theme_classic()
p

p <- ggplot(bwe.pot, aes(x = pot, y = Cseverity, fill = treatment)) + 
  scale_fill_manual(values = c("white", "grey")) +
  geom_violin(position = position_dodge(1)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(1), dotsize  = 0.5) +
  stat_summary(fun.y = mean, geom = "point", size = 3, color = "red", position = position_dodge(1)) +
  labs(x = "Bin", y = "Laby cells / mg") +
  theme_classic()
p

bargraph.CI(x.factor = treatment,
            group = diversity,
            response = Cseverity.round,
            data = bwe.pot,
            ylim = c(0,500), ylab = "disease cells/mg",
            xlab = "Temperature Treatment", legend = T)
bargraph.CI(x.factor = diversity,
            response = Cseverity.round,
            data = bwe.pot,
            ylim = c(0,500), ylab = "disease cells/mg",
            xlab = "Diversity", legend = T)

##Cell INTENSITY only plants with disease
#Cintensity.model <- glm(Cseverity.round ~ treatment/diversity, family = poisson, data = filter(bwe.pot, Cprevalence > 0))
#Anova(Cintensity.model)

hist(bwe.pot.Cintensity$Cintensity.sqrt)

Cintensity.model <- aov(Cintensity.sqrt ~ diversity * treatment + Error(bin), data = bwe.pot.Cintensity)
summary(Cintensity.model)

Cintensity.model <- aov(Cintensity.sqrt ~ diversity * treatment + Error(bin), data = bwe.bin.Cintensity)
summary(Cintensity.model)

Cintensity.model2 <- aov(Cintensity.sqrt ~ diversity * treatment, data = bwe.bin.Cintensity)
summary(Cintensity.model2)

plot(Cintensity.model2)
hist(residuals(Cintensity.model2))
shapiro.test(residuals(Cintensity.model2))
leveneTest(Cintensity.model2)

#Figure
p <- ggplot(bwe.pot.Cintensity, aes(x = treatment, y = Cintensity, fill = diversity)) + 
  scale_fill_manual(values = c("white", "grey")) +
  geom_violin(position = position_dodge(1)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(1), dotsize  = 0.5) +
  #stat_summary(fun.y = mean, geom = "point", size = 3, color = "red", position = position_dodge(1)) +
  labs(x = "Temperature Treatment", y = "Laby cells / mg in diseased tissue") +
  ylim(0, 100) +
  theme_classic()
p

p <- ggplot(bwe.pot.Cintensity, aes(x = bin, y = Cintensity, fill = treatment)) +
  scale_fill_manual(values = c("white", "grey")) +
  geom_violin(position = position_dodge(1)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(1), dotsize  = 0.5) +
  stat_summary(fun.y = mean, geom = "point", size = 3, color = "red", position = position_dodge(1)) +
  labs(x = "Bin", y = "Laby cells / mg in diseased tissue") +
  theme_classic()
p

bargraph.CI(x.factor = treatment,
            group = diversity,
            response = Cintensity,
            data = bwe.bin.Cintensity,
            ylim = c(0,1500), ylab = "cells/mg",
            xlab = "Temperature Treatment", legend = T)

bargraph.CI(x.factor = treatment,
            group = diversity,
            response = Cintensity,
            data = bwe.pot.Cintensity,
            ylim = c(0,2000), ylab = "cells/mg",
            xlab = "Temperature Treatment", legend = T)

#Zero inflated glm
#Poisson glm or negative binomial (start with poisson)
```

##Genotype performance
```{r}
##Lesion Prevalence
genotype.model <- glm(cbind(lesion, lesion.absent) ~ genotype*treatment + bin/pot, data = filter(bwe, diversity == "mono"), family = binomial)
anova(genotype.model)

mycols.genotype <- cb[c("blue", "grey", "green" , "orange", "pink", "red", "white", "yellow")] #brown = grey, and purple = pink
mycols.genotype.treatment <- cb[c("blue", "blue", "grey", "grey", "green", "green", "orange", "orange", "pink", "pink", "red", "red", "white", "white", "yellow", "yellow")]

bargraph.CI(x.factor = genotype,
            response = lesion,
            data = filter(bwe, diversity == "mono"),
            ylim = c(0,1.1), ylab = "Proportion of shoots with lesions",
            xlab = "Genotype", legend = T,
            col = mycols.genotype)

#Lesion severity
genotype.model <- aov(lc.FS ~ genotype + bin/pot, data = filter(bwe, diversity == "mono" & lesion > 0))
summary(genotype.model)

bargraph.CI(x.factor = genotype,
            response = lc.FS,
            data = filter(bwe, diversity == "mono" & lesion > 0),
            ylim = c(0,15), ylab = "Lesion percent cover",
            xlab = "Genotype", legend = T,
            col = mycols.genotype)

#Cell prevalence
genotype.model <- aov(Cprevalence ~ pot + bin/pot, data = filter(bwe.pot, diversity == "mono"))
summary(genotype.model)

genotype.model <- glm(cbind(lesion, lesion.absent) ~ genotype*treatment + bin/pot, data = filter(bwe, diversity == "mono"), family = binomial)
anova(genotype.model)

bargraph.CI(x.factor = pot,
            response = Cprevalence,
            data = filter(bwe.pot, diversity == "mono"),
            ylim = c(0,1), ylab = "Proportion of shoots with disease cells",
            xlab = "Genotype", legend = T,
            col = mycols.genotype)

#binomial
genotype.model <- glm(cbind(cells.present, cells.absent) ~ genotype + bin/pot, na.action = na.omit, data = filter(bwe, diversity == "mono"), family = binomial)
anova(genotype.model, test = "LR")

bargraph.CI(x.factor = genotype,
            response = cells.present,
            data = filter(bwe, diversity == "mono"),
            ylim = c(0,1), ylab = "Proportion of shoots with disease cells",
            xlab = "Genotype", legend = T,
            col = mycols.genotype)

#Cell Severity
genotype.model <- aov(log(Cseverity+1) ~ pot + bin, data = filter(bwe.pot, diversity == "mono"))
summary(genotype.model)

###INTENSITY
genotype.model <- aov(log(cell.mg+1) ~ genotype + bin/pot, data = filter(bwe, diversity == "mono", cells.present > 0))
summary(genotype.model)

bargraph.CI(x.factor = genotype,
            response = log(cell.mg+1),
            data = filter(bwe, diversity == "mono", cells.present > 0),
            ylim = c(0,5), ylab = "log(cells/mg +1)",
            xlab = "Genotype", legend = T,
            col = mycols.genotype)
```





#cell count/mg by genotype, diversity treatment, and temp. treatment
```{r}
bargraph.CI(x.factor = genotype,
            group = diversity,
            response = log(cell.mg + 1),
            data = filter(d04DEC1, cell.mg > 0), #do i want to exclude polys?
            ylim = c(0,10), ylab = "Log(cells per mg + 1)",
            xlab = "Genotype", legend = T)

bargraph.CI(x.factor = diversity,
            response = log(cell.mg + 1),
            data = filter(d04DEC1, cell.mg > 0),
            ylim = c(0,4), ylab = "Log(cells per mg + 1)",
            xlab = "Diversity Treatment")

bargraph.CI(x.factor = treatment,
            response = log(cell.mg + 1),
            data = filter(d04DEC1, cell.mg >0),
            ylim = c(0,4), ylab = "Log(cells per mg + 1)",
            xlab = "Temperature Treatment")

bargraph.CI(x.factor = treatment,
            group = diversity,
            response = log(cell.mg + 1),
            data = filter(d04DEC1, cell.mg > 0),
            ylim = c(0,4), ylab = "Log(cells per mg + 1)",
            xlab = "Diversity Treatment")
```

#cell presence by genotype, diversity treatment, and temp. treatment
```{r}
bargraph.CI(x.factor = genotype,
            group = diversity,
            response = cells.present,
            data = filter(d04DEC1),
            ylim = c(0,1),
            ylab = "Proportion of samples with cells present",
            xlab = "Genotype",
            uc = F, lc = F)

bargraph.CI(x.factor = diversity,
            response = cells.present,
            data = d04DEC1,
            ylim = c(0,1),
            ylab = "Proportion of samples with cells present",
            xlab = "Diversity Treatment",
            uc = F, lc = F)

bargraph.CI(x.factor = treatment,
            response = cells.present,
            data = d04DEC1,
            ylim = c(0,1),
            ylab = "Proportion of samples with cells present",
            xlab = "Temperature Treatment",
            uc = F, lc = F)

bargraph.CI(x.factor = treatment,
            group = diversity,
            response = cells.present,
            data = d04DEC1,
            ylim = c(0,1),
            ylab = "Proportion of samples with cells present",
            xlab = "Temperature Treatment",
            uc = F, lc = F)
```

#cell count per mg by lesion percent cover
```{r}
bwe.intensity <- filter(bwe, cell.mg > 0)

plot(bwe.intensity$lc.FS, log(bwe.intensity$cell.mg+1),
     xlab = "Lesion percent cover",
     ylab = "Log(cells per mg + 1)",
     main = "Lesion Intensity vs. Cell Intensity",
     ylim = c(0,10),
     xlim = c(0,100))

plot(bwe$lc.FS, log(bwe$cell.mg+1),
     xlab = "Lesion percent cover",
     ylab = "Log(cells per mg +1)",
     main = "Lesion % cover vs. Cell count/mg",
     ylim = c(0,10),
     xlim = c(0,50))
```

#Cell presence (qPCR) vs. lesion presence (visual)
```{r}
table.1 <- table(bwe$lesion, bwe$cells.present)

table.1

mosaicplot(table.1, main ="",
xlab = "lesion presence",
           ylab = "cell presence",
           col = T)

table.2 <- table(bwe$lesion.group, bwe$cells.present)
table.2

table.2 <- matrix(c(20,0,41,1,206,33,25,22),ncol=2,byrow=TRUE)
colnames(table.2) <- c("absent","present")
rownames(table.2) <- c("0","<1","<10",">10")
table.2 <- as.table(table.2)
table.2

mosaicplot(table.2, main = "",
           xlab = "lesion percent cover",
           ylab = "cell presence",
           col = T)
```




