---
title: "PrelimAnalysis_19SEP2017"
author: "Forest Schenck"
date: "September 19, 2017"
output: pdf_document
---

#PACKAGES
```{r}
library(dplyr)
library(sciplot)
library(car)
```

#Importing/wrangling data
```{r}
bwe <- read.csv("bwe_data_04DEC2017.csv") #importing from dropbox
str(bwe)

bwe$rep <- as.factor(bwe$rep)
bwe$bin <- as.factor(bwe$bin)

bwe.pot <- bwe %>%
  group_by(diversity, pot, treatment, bin, rep) %>%
  summarize(Lprevalence = mean(lesion, na.rm = T), Lseverity = mean(lc.FS, na.rm = T), Cprevalence = mean(cells.present, na.rm = T), Cseverity = mean(cell.mg, na.rm = T))

str(bwe.pot)
head(bwe.pot)
```

#ANALYSES
##Lesion Prevalence
```{r}
#Analyses
Lprev.model <- aov(Lprevalence ~ diversity * treatment + Error(bin), data = bwe.pot)
summary(Lprev.model)

#Figure
bargraph.CI(x.factor = treatment,
            response = Lprevalence,
            data = bwe.pot,
            ylim = c(0,1.1), ylab = "Proportion of shoots with lesions",
            xlab = "Temperature Treatment", legend = T)
```

##Lesion severity
```{r}
#Analyses
Lsev.model <- aov(Lseverity ~ diversity * treatment + Error(bin), data = bwe.pot)
summary(Lsev.model)

#Figure
bargraph.CI(x.factor = treatment,
            response = Lseverity,
            data = bwe.pot,
            ylim = c(0,10), ylab = "Mean lesion percent cover",
            xlab = "Temperature Treatment", legend = T)
```

##Cell Prevalence
```{r}
#Analyses
Cprev.model <- aov(Cprevalence ~ diversity * treatment + Error(bin), data = bwe.pot)
summary(Cprev.model)
```

##Cell severity
```{r}
#Analyses ##DATA IS NOT NORMALLY DISTRIBUTED?
Csev.model <- aov(Cseverity ~ diversity * treatment + Error(bin), data = bwe.pot)
summary(Csev.model)

#checking assumptions
Csev.model.2 <- aov(Cseverity ~ diversity * treatment + bin, data = bwe.pot)
summary(Csev.model.2)
plot(Csev.model.2, 1)
plot(Csev.model.2, 2)
plot(Csev.model.2, 5)
boxCox(Csev.model.2)

bargraph.CI(x.factor = treatment,
            response = log(Cseverity+1),
            data = bwe.pot,
            ylim = c(0,2), ylab = "Log(cells/mg+1)",
            xlab = "Temperature Treatment", legend = T)

##only for pots with disease -->intensity MODEL INCORRECT
Cintensity.model <- aov(log(Cseverity + 1) ~ treatment * diversity + Error(bin), data = filter(bwe.pot, Cprevalence > 0))
summary(Cintensity.model)

#Figure
bargraph.CI(x.factor = treatment,
            response = log(Cseverity+1),
            data = filter(bwe.pot, Cprevalence > 0),
            ylim = c(0,5), ylab = "Log(cells/mg)",
            xlab = "Temperature Treatment", legend = T)
##only for monocultures
Cintensity.model <- aov(log(Cseverity + 1) ~ treatment + Error(bin), data = filter(bwe.pot, diversity == "mono"))
summary(Cintensity.model)
```






#cell count/mg by genotype, diversity treatment, and temp. treatment
```{r}
bargraph.CI(x.factor = genotype,
            group = diversity,
            response = log(cell.mg + 1),
            data = filter(d04DEC1, cell.mg > 0), #do i want to exclude polys?
            ylim = c(0,10), ylab = "Log(cells per mg + 1)",
            xlab = "Genotype", legend = T)

bargraph.CI(x.factor = diversity,
            response = log(cell.mg + 1),
            data = filter(d04DEC1, cell.mg > 0),
            ylim = c(0,4), ylab = "Log(cells per mg + 1)",
            xlab = "Diversity Treatment")

bargraph.CI(x.factor = treatment,
            response = log(cell.mg + 1),
            data = filter(d04DEC1, cell.mg >0),
            ylim = c(0,4), ylab = "Log(cells per mg + 1)",
            xlab = "Temperature Treatment")

bargraph.CI(x.factor = treatment,
            group = diversity,
            response = log(cell.mg + 1),
            data = filter(d04DEC1, cell.mg > 0),
            ylim = c(0,4), ylab = "Log(cells per mg + 1)",
            xlab = "Diversity Treatment")
```

#cell presence by genotype, diversity treatment, and temp. treatment
```{r}
bargraph.CI(x.factor = genotype,
            group = diversity,
            response = cells.present,
            data = filter(d04DEC1),
            ylim = c(0,1),
            ylab = "Proportion of samples with cells present",
            xlab = "Genotype",
            uc = F, lc = F)

bargraph.CI(x.factor = diversity,
            response = cells.present,
            data = d04DEC1,
            ylim = c(0,1),
            ylab = "Proportion of samples with cells present",
            xlab = "Diversity Treatment",
            uc = F, lc = F)

bargraph.CI(x.factor = treatment,
            response = cells.present,
            data = d04DEC1,
            ylim = c(0,1),
            ylab = "Proportion of samples with cells present",
            xlab = "Temperature Treatment",
            uc = F, lc = F)

bargraph.CI(x.factor = treatment,
            group = diversity,
            response = cells.present,
            data = d04DEC1,
            ylim = c(0,1),
            ylab = "Proportion of samples with cells present",
            xlab = "Temperature Treatment",
            uc = F, lc = F)
```

#cell count per mg by lesion percent cover
```{r}
d04DEC1.intensity <- filter(d04DEC1, cell.mg > 0)

plot(d04DEC1.intensity$lc.FS, log(d04DEC1.intensity$cell.mg+1),
     xlab = "Lesion percent cover",
     ylab = "Log(cells per mg + 1)",
     main = "Lesion Intensity vs. Cell Intensity",
     ylim = c(0,10),
     xlim = c(0,100))

plot((d04DEC1$lc.FS), log(d04DEC1$cell.mg+1),
     xlab = "Lesion percent cover",
     ylab = "Log(cells per mg +1)",
     main = "Lesion % cover vs. Cell count/mg",
     ylim = c(0,10),
     xlim = c(0,100))
```

#Cell presence (qPCR) vs. lesion presence (visual)
```{r}
table.1 <- table(d04DEC1$lesion, d04DEC1$cells.present)

table.1

mosaicplot(table.1, main ="",
xlab = "lesion presence",
           ylab = "cell presence",
           col = T)

table.2 <- table(d04DEC1$lesion.group, d04DEC1$cells.present)
table.2

table.2 <- matrix(c(15,1,25,1,151,23,23,19),ncol=2,byrow=TRUE)
colnames(table.2) <- c("absent","present")
rownames(table.2) <- c("0","<1","<10",">10")
table.2 <- as.table(table.2)
table.2

mosaicplot(table.2, main = "",
           xlab = "lesion percent cover",
           ylab = "cell presence",
           col = T)
```




