---
title: "Zosterapalooza 2018 figures"
author: "Forest Schenck"
date: "3/20/2018"
output: pdf_document
---


#Zosterapalooza 2018 figures
```{r}
source("http://faraway.neu.edu/data/Rprofile")
```


#Lesion prevalence
```{r}
bwe.pot.prevplot <- aggregate(Lprevalence ~ treatment, data = filter(bwe.pot.xbin1, treatment != "pulse"), mean)

bwe.pot.prevplot$treatment.name <- c("Cool", "Warm")

mycols <- cb[c("blue", "red")]
mycols

p <- ggplot(bwe.pot.prevplot, aes(x= treatment.name, y = Lprevalence, fill = treatment)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("cold" = "#0072B2", "hot" = "#D55E00")) +
  labs(x = "", y = "") +
  theme_classic() +
  theme(axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20, vjust = -4),
        axis.title.y = element_text(size = 20, vjust = 4))
    
p
```

#Lesion intensity
```{r}
bwe.pot.intplot <- bwe.pot.Lintensity %>%
  filter(treatment != "pulse") %>%
  filter(bin != "1") %>%
  group_by(treatment) %>%
  summarize(Lintensity.mean = mean(Lintensity), Lintensity.se = se(Lintensity, na.rm = T))

bwe.pot.intplot$treatment.name <- c("Cool", "Warm")

p <- ggplot(bwe.pot.intplot, aes(x = treatment, y = Lintensity.mean*100, fill = treatment)) + 
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("cold" = "#0072B2", "hot" = "#D55E00")) +
  geom_errorbar(aes(ymin=(Lintensity.mean*100)-(Lintensity.se*100), ymax=(Lintensity.mean*100)+(Lintensity.se*100)), width=.1, position=position_dodge(1)) +
  geom_line(position=position_dodge(1)) +
  ylim(0,20) +
  labs(x = "", y = "") +
  theme_classic() +
  theme(axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20, vjust = -4),
        axis.title.y = element_text(size = 20, vjust = 4))
p

bwe.extreme.lesions <- bwe %>%
  filter(sampled == "1") %>%
  filter(lc.FS > 0) %>%
  filter(treatment != "pulse") %>%
  filter(bin != "1") #%>%
  filter(treatment != "hot")
```

#Cell prevalence
```{r}
bwe.pot.prevcell <- aggregate(Cprevalence ~ treatment, data = filter(bwe.pot.xbin1, treatment != "pulse"), mean)

bwe.pot.prevcell$treatment.name <- c("Cool", "Warm")

p <- ggplot(bwe.pot.prevcell, aes(x = treatment.name, y = Cprevalence, fill = treatment)) + 
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("cold" = "#0072B2", "hot" = "#D55E00")) +
  labs(x = "", y = "") +
  ylim(0,1) +
  theme_classic() +
  theme(axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20, vjust = -4),
        axis.title.y = element_text(size = 20, vjust = 4))
p
```

#Cell intensity
```{r}
bwe.pot.intcell <- bwe.pot.Cintensity %>%
  group_by(treatment, diversity) %>%
  summarize(Cintensity.mean = log(mean(Cintensity)), Cintensity.se = log(se(Cintensity, na.rm = T)))

bwe.pot.intcell$treatment.name <- c("Cool", "Cool", "Warm", "Warm")
bwe.pot.intcell$diversity.temp <- c("MCool", "PCool", "MWarm", "PWarm")
str(bwe.pot.intcell)

p <- ggplot(bwe.pot.intcell, aes(x = treatment.name, y = Cintensity.mean, fill = diversity.temp)) + 
  geom_bar(stat = "identity", position = "dodge", colour = "white") +
  scale_fill_manual(values = c("#0072B2", "#D55E00", "#0072B2", "#D55E00")) +
  geom_errorbar(aes(ymin=Cintensity.mean-Cintensity.se, ymax=Cintensity.mean+Cintensity.se), width=.1, position=position_dodge(0.9)) +
  #geom_line(position=position_dodge(.5)) +
  labs(x = "", y = "") +
  theme_classic() +
  theme(axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20))
p

```



